### ISSUE TITLE
Status of website

### ISSUE THREAD

**Issue by premasagar** [publicwhip/publicwhip#18]
Currently, publicwhip.org.uk is down (`"Unable to access database"`). Hopefully it can be brought back online quickly, but this is a question about ongoing support of the site. I noticed that while Commons votes have been keeping up-to-date, there have not been any Lords divisions this parliament. Is that something that is likely to be fixed?

PublicWhip is an outstanding public service. I imagine that those behind it are busy people with other responsibilities. I hope the site can continue, as it offers something unique and important. However, if it cannot, it would be helpful to know its status.

**Comment by rbairwell** [comment]
Hi,

We're currently upgrading the server due to a could of problems starting around 12.30 today. It should be back up shortly.

**Comment by rbairwell** [comment]
The site is back up and running now (sorry for that) and is stabilising.

**Comment by premasagar** [comment]
Thanks so much. I'm glad the site is still alive. And I see that Lords divisions are there now too. Great stuff.
