### ISSUE TITLE
PublicWhip curently down 

### ISSUE THREAD

**Issue by RichardTaylor** [publicwhip/publicwhip#37]
I'm currently seeing an error from Cloudfare when trying to access 

https://www.publicwhip.org.uk/

> Error 522 
>Connection timed out
>...
>An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources.

This was not directly connected to anything I was doing. I wasn't doing anything on the site prior to seeing the error.

**Comment by rbairwell** [comment]
Hi @RichardTaylor ,

There's currently the tail end of a server/datacenter migration going on and so things are being a little bit "flaky" (we were expecting the outage to be a couple of minutes at most - our other server was offline for less than 5 minutes). We're hoping normal service will be resumed very shortly.

Thanks,
Richard
