### ISSUE TITLE
Footer overlapping content and making it unreadable / unuseable. Impacts functionality including login. 

### ISSUE THREAD

**Issue by RichardTaylor** [publicwhip/publicwhip#39]
The login form accessible [to me] via "edit" links has stopped working. 

I can work around it in Firefox via Tools >  Browser Tools > Web Developer Tools > Style Editor and deleting the style sheet. 

The text boxes for username and password were not clickable, I could not type in them. 

I can't select the text around the boxes either, but I can select other text on the page, as shown in the attached video. 

The issue occurs on both Safari and Firefox for me. 

https://user-images.githubusercontent.com/547695/189703552-7610e5a6-3662-476b-afc6-0fd5fa728fff.mov

**Comment by RichardTaylor** [comment]
This appears to be a special case of a general new bug which appears to affect content which is overlapped by the silhouette image on the page footer.

**Comment by RichardTaylor** [comment]
This is impacting other pages too eg. preventing reading and following links on policy pages. 

The footer is crashing into the content. 

<img width="1064" alt="Screenshot 2022-09-12 at 20 25 20" src="https://user-images.githubusercontent.com/547695/189738756-589ca05f-22ff-43c9-adc2-af0ed9f83658.png">

**Comment by RichardTaylor** [comment]
This issue breaks, or makes tedious (via the workaround of turning the styles off), quite a lot of site functionality. 

Archive.org shows the issue arose since 5 September. 

See

http://web.archive.org/web/20220905064631/https://www.publicwhip.org.uk/

vs 13 September 

http://web.archive.org/web/20220913095635/https://www.publicwhip.org.uk/


>I can work around it in Firefox via Tools > Browser Tools > Web Developer Tools > Style Editor and deleting the style sheet.

Firefox also has a view > Page style > No style  option

**Comment by rbairwell** [comment]
I'm looking into this now. Sorry for the delay

**Comment by rbairwell** [comment]
Should be fixed now. Sorry about that - seems a closing div tag was missing.
